export const IN_POSITION_LOCATION = 0;
export const IN_NORMAL_LOCATION = 1;
export const IN_MATERIAL_REF_LOCATION = 2;
export const IN_TEX_COORD_LOCATION = 3;

export const TRANSFORMS_UBO_BINDING_INDEX = 0;
export const LIGHT_CONFIG_UBO_BINDING_INDEX = 1;
export const MATERIAL_CONFIG_UBO_BINDING_INDEX = 2;
export const OVERLAY_UBO_BINDING_INDEX = 3;
