// This file is generated. Edit constants.ts instead.
#define IN_POSITION_LOCATION 0
#define IN_NORMAL_LOCATION 1
#define IN_NORMAL_REF_LOCATION 1
#define IN_DIRECTION_LOCATION 1
#define IN_MATERIAL_REF_LOCATION 2
#define IN_INSTANCE_COLOR_LOCATION 2
#define IN_TEX_COORD_LOCATION 3
#define IN_INSTANCE_MODEL_TRANSFORM_LOCATION 4
