# Copyright (c) 2025-2026 Gene Ressler
# SPDX-License-Identifier: GPL-3.0-or-later

# Emit an OBJ file for the truck sign model.

# Extracted from truck model.
X0 = -5.999
X1 = -0.799
Y0 = 1.124
Y1 = 3.274
Z0 = -1.302
Z1 = 1.298
# The logo texture is centered in the png with padding so CLAMP_TO_EDGE works.
# WebGL does not support CLAMP_TO_BORDER.
TEX_MARGIN_X = 0
TEX_X0 = -TEX_MARGIN_X
TEX_X1 = 1 + TEX_MARGIN_X
HALF_HEIGHT = (0.5 + TEX_MARGIN_X) * (Y1 - Y0) / (X1 - X0)
TEX_Y0 = 0.5 + HALF_HEIGHT
TEX_Y1 = 0.5 - HALF_HEIGHT

# fmt: off
POSITIONS = [
  X0, Y0, Z0, # 0
  X1, Y0, Z0, # 1
  X1, Y1, Z0, # 2
  X0, Y1, Z0, # 3
  X0, Y0, Z1, # 4
  X1, Y0, Z1, # 5
  X1, Y1, Z1, # 6
  X0, Y1, Z1, # 7
]

NORMALS =[
  0, 0, -1, # 0    
  0, 0, 1, # 1
]

TEX_COORDS = [
  TEX_X0, TEX_Y0,
  TEX_X1, TEX_Y0,
  TEX_X1, TEX_Y1,
  TEX_X0, TEX_Y1,
]

POSITION_INDICES = [
  2, 1, 0, # 0
  0, 3, 2, # 1
  4, 5, 6, # 2
  6, 7, 4, # 3
]

NORMAL_INDICES = [
  0, 0, 0, # 0
  0, 0, 0, # 1
  1, 1, 1, # 2
  1, 1, 1, # 3
]

TEX_INDICES = [
  3, 0, 1,
  1, 2, 3,
  0, 1, 2,
  2, 3, 0,
]
# fmt: on


def main():
    with open("truck-sign.obj", "w") as out_file:
        print("# Generated by build-truck-sign.py", file=out_file);
        print("# option: texCoords = yes", file=out_file)
        for i in range(0, len(POSITIONS), 3):
            p = f"v {POSITIONS[i]} {POSITIONS[i+1]} {POSITIONS[i+2]}"
            print(p, file=out_file)
        for i in range(0, len(NORMALS), 3):
            p = f"vn {NORMALS[i]} {NORMALS[i+1]} {NORMALS[i+2]}"
            print(p, file=out_file)
        for i in range(0, len(TEX_COORDS), 2):
            p = f"vt {TEX_COORDS[i]} {TEX_COORDS[i+1]}"
            print(p, file=out_file)
        for i in range(0, len(POSITION_INDICES), 3):
            p = f"f {1+POSITION_INDICES[i]}/{1+TEX_INDICES[i]}/{1+NORMAL_INDICES[i]}"
            p += f" {1+POSITION_INDICES[i+1]}/{1+TEX_INDICES[i+1]}/{1+NORMAL_INDICES[i+1]}"
            p += f" {1+POSITION_INDICES[i+2]}/{1+TEX_INDICES[i+2]}/{1+NORMAL_INDICES[i+2]}"
            print(p, file=out_file)

main()
